#project 'clienttest.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def common_pods
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
    pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true
    pod 'Bolts-Swift'
    pod 'Alamofire', '~> 4.0'
end

target 'Universities' do
    common_pods
end

